/**
 * Destiny Board Node Names for mapping
 * Used by destinyMapping.ts for character sync
 */

// Organized by category
export const DESTINY_BOARD_NODES = {
  // Warrior Weapons
  warrior: {
    axe: [
      'Axe Fighter',
      'Battleaxe Combat Specialist',
      'Greataxe Combat Specialist',
      'Halberd Combat Specialist',
      'Carrioncaller Combat Specialist',
      'Infernal Scythe Combat Specialist',
      'Bear Paws Combat Specialist',
      'Realmbreaker Combat Specialist',
    ],
    sword: [
      'Sword Fighter',
      'Broadsword Combat Specialist',
      'Claymore Combat Specialist',
      'Dual Swords Combat Specialist',
      'Clarent Blade Combat Specialist',
      'Carving Sword Combat Specialist',
      'Galatine Pair Combat Specialist',
      'Kingmaker Combat Specialist',
    ],
    mace: [
      'Mace Fighter',
      'Mace Combat Specialist',
      'Heavy Mace Combat Specialist',
      'Morning Star Combat Specialist',
      'Bedrock Mace Combat Specialist',
      'Incubus Mace Combat Specialist',
      'Camlann Mace Combat Specialist',
      'Oathkeepers Combat Specialist',
    ],
    hammer: [
      'Hammer Fighter',
      'Hammer Combat Specialist',
      'Polehammer Combat Specialist',
      'Great Hammer Combat Specialist',
      'Tombhammer Combat Specialist',
      'Forge Hammers Combat Specialist',
      'Grovekeeper Combat Specialist',
      'Hand of Justice Combat Specialist',
    ],
    wargloves: [
      'War Gloves Fighter',
      'Brawler Gloves Combat Specialist',
      'Battle Bracers Combat Specialist',
      'Spiked Gauntlets Combat Specialist',
      'Ravenstrike Cestus Combat Specialist',
      'Hellfire Hands Combat Specialist',
      'Fists of Avalon Combat Specialist',
      'Ursine Maulers Combat Specialist',
    ],
  },
  // Hunter Weapons
  hunter: {
    bow: [
      'Bow Fighter',
      'Bow Combat Specialist',
      'Warbow Combat Specialist',
      'Longbow Combat Specialist',
      'Whispering Bow Combat Specialist',
      'Wailing Bow Combat Specialist',
      'Bow of Badon Combat Specialist',
      'Mistpiercer Combat Specialist',
    ],
    crossbow: [
      'Crossbow Fighter',
      'Crossbow Combat Specialist',
      'Heavy Crossbow Combat Specialist',
      'Light Crossbow Combat Specialist',
      'Weeping Repeater Combat Specialist',
      'Boltcasters Combat Specialist',
      'Siegebow Combat Specialist',
      'Energy Shaper Combat Specialist',
    ],
    spear: [
      'Spear Fighter',
      'Spear Combat Specialist',
      'Pike Combat Specialist',
      'Glaive Combat Specialist',
      'Heron Spear Combat Specialist',
      'Spirithunter Combat Specialist',
      'Trinity Spear Combat Specialist',
      'Daybreaker Combat Specialist',
    ],
    dagger: [
      'Dagger Fighter',
      'Dagger Combat Specialist',
      'Dagger Pair Combat Specialist',
      'Claws Combat Specialist',
      'Bloodletter Combat Specialist',
      'Black Hands Combat Specialist',
      'Deathgivers Combat Specialist',
      'Bridled Fury Combat Specialist',
    ],
    quarterstaff: [
      'Quarterstaff Fighter',
      'Quarterstaff Combat Specialist',
      'Iron-clad Staff Combat Specialist',
      'Double Bladed Staff Combat Specialist',
      'Black Monk Stave Combat Specialist',
      'Soulscythe Combat Specialist',
      'Staff of Balance Combat Specialist',
      'Grailseeker Combat Specialist',
    ],
  },
  // Mage Weapons
  mage: {
    firestaff: [
      'Fire Staff Fighter',
      'Fire Staff Combat Specialist',
      'Great Fire Staff Combat Specialist',
      'Infernal Staff Combat Specialist',
      'Wildfire Staff Combat Specialist',
      'Blazing Staff Combat Specialist',
      'Brimstone Staff Combat Specialist',
      'Dawnsong Combat Specialist',
    ],
    holystaff: [
      'Holy Staff Fighter',
      'Holy Staff Combat Specialist',
      'Great Holy Staff Combat Specialist',
      'Divine Staff Combat Specialist',
      'Lifetouch Staff Combat Specialist',
      'Fallen Staff Combat Specialist',
      'Redemption Staff Combat Specialist',
      'Hallowfall Combat Specialist',
    ],
    arcanestaff: [
      'Arcane Staff Fighter',
      'Arcane Staff Combat Specialist',
      'Great Arcane Staff Combat Specialist',
      'Enigmatic Staff Combat Specialist',
      'Witchwork Staff Combat Specialist',
      'Occult Staff Combat Specialist',
      'Malevolent Locus Combat Specialist',
      'Evensong Combat Specialist',
    ],
    froststaff: [
      'Frost Staff Fighter',
      'Frost Staff Combat Specialist',
      'Great Frost Staff Combat Specialist',
      'Glacial Staff Combat Specialist',
      'Hoarfrost Staff Combat Specialist',
      'Icicle Staff Combat Specialist',
      'Permafrost Prism Combat Specialist',
      'Chillhowl Combat Specialist',
    ],
    cursedstaff: [
      'Cursed Staff Fighter',
      'Cursed Staff Combat Specialist',
      'Great Cursed Staff Combat Specialist',
      'Demonic Staff Combat Specialist',
      'Cursed Skull Combat Specialist',
      'Damnation Staff Combat Specialist',
      'Lifecurse Staff Combat Specialist',
      'Shadowcaller Combat Specialist',
    ],
    naturestaff: [
      'Nature Staff Fighter',
      'Nature Staff Combat Specialist',
      'Great Nature Staff Combat Specialist',
      'Wild Staff Combat Specialist',
      'Druidic Staff Combat Specialist',
      'Blight Staff Combat Specialist',
      'Rampant Staff Combat Specialist',
      'Ironroot Staff Combat Specialist',
    ],
  },
  // Plate Armor
  plate: {
    helmet: [
      'Plate Helmet Fighter',
      'Soldier Helmet Specialist',
      'Knight Helmet Specialist',
      'Guardian Helmet Specialist',
      'Royal Helmet Specialist',
      'Demon Helmet Specialist',
      'Judicator Helmet Specialist',
      'Helmet of Valor Specialist',
    ],
    armor: [
      'Plate Armor Fighter',
      'Soldier Armor Specialist',
      'Knight Armor Specialist',
      'Guardian Armor Specialist',
      'Royal Armor Specialist',
      'Demon Armor Specialist',
      'Judicator Armor Specialist',
      'Armor of Valor Specialist',
    ],
    boots: [
      'Plate Boots Fighter',
      'Soldier Boots Specialist',
      'Knight Boots Specialist',
      'Guardian Boots Specialist',
      'Royal Boots Specialist',
      'Demon Boots Specialist',
      'Judicator Boots Specialist',
      'Boots of Valor Specialist',
    ],
  },
  // Leather Armor
  leather: {
    hood: [
      'Leather Hood Fighter',
      'Mercenary Hood Specialist',
      'Hunter Hood Specialist',
      'Assassin Hood Specialist',
      'Hood of Tenacity Specialist',
      'Hellion Hood Specialist',
      'Stalker Hood Specialist',
      'Specter Hood Specialist',
    ],
    jacket: [
      'Leather Jacket Fighter',
      'Mercenary Jacket Specialist',
      'Hunter Jacket Specialist',
      'Assassin Jacket Specialist',
      'Jacket of Tenacity Specialist',
      'Hellion Jacket Specialist',
      'Stalker Jacket Specialist',
      'Specter Jacket Specialist',
    ],
    shoes: [
      'Leather Shoes Fighter',
      'Mercenary Shoes Specialist',
      'Hunter Shoes Specialist',
      'Assassin Shoes Specialist',
      'Shoes of Tenacity Specialist',
      'Hellion Shoes Specialist',
      'Stalker Shoes Specialist',
      'Specter Shoes Specialist',
    ],
  },
  // Cloth Armor
  cloth: {
    cowl: [
      'Cloth Cowl Fighter',
      'Scholar Cowl Specialist',
      'Cleric Cowl Specialist',
      'Mage Cowl Specialist',
      'Royal Cowl Specialist',
      'Fiend Cowl Specialist',
      'Cultist Cowl Specialist',
      'Cowl of Purity Specialist',
    ],
    robe: [
      'Cloth Robe Fighter',
      'Scholar Robe Specialist',
      'Cleric Robe Specialist',
      'Mage Robe Specialist',
      'Royal Robe Specialist',
      'Fiend Robe Specialist',
      'Cultist Robe Specialist',
      'Robe of Purity Specialist',
    ],
    sandals: [
      'Cloth Sandals Fighter',
      'Scholar Sandals Specialist',
      'Cleric Sandals Specialist',
      'Mage Sandals Specialist',
      'Royal Sandals Specialist',
      'Fiend Sandals Specialist',
      'Cultist Sandals Specialist',
      'Sandals of Purity Specialist',
    ],
  },
  // Off-hand
  offhand: {
    shield: [
      'Shield Fighter',
      'Shield Specialist',
      'Sarcophagus Specialist',
      'Caitiff Shield Specialist',
      'Facebreaker Specialist',
      'Astral Aegis Specialist',
    ],
    torch: [
      'Torch Fighter',
      'Torch Specialist',
      'Mistcaller Specialist',
      'Leering Cane Specialist',
      'Cryptcandle Specialist',
      'Sacred Scepter Specialist',
    ],
    tome: [
      'Tome Fighter',
      'Tome of Spells Specialist',
      'Eye of Secrets Specialist',
      'Muisak Specialist',
      'Taproot Specialist',
      'Celestial Censer Specialist',
    ],
  },
  // Gathering
  gathering: {
    fiber: [
      'Fiber Harvester',
      'Novice Fiber Harvester',
      'Journeyman Fiber Harvester',
      'Adept Fiber Harvester',
      'Expert Fiber Harvester',
      'Master Fiber Harvester',
      'Grandmaster Fiber Harvester',
      'Elder Fiber Harvester',
    ],
    hide: [
      'Hide Skinner',
      'Novice Hide Skinner',
      'Journeyman Hide Skinner',
      'Adept Hide Skinner',
      'Expert Hide Skinner',
      'Master Hide Skinner',
      'Grandmaster Hide Skinner',
      'Elder Hide Skinner',
    ],
    ore: [
      'Ore Miner',
      'Novice Ore Miner',
      'Journeyman Ore Miner',
      'Adept Ore Miner',
      'Expert Ore Miner',
      'Master Ore Miner',
      'Grandmaster Ore Miner',
      'Elder Ore Miner',
    ],
    rock: [
      'Rock Quarrier',
      'Novice Rock Quarrier',
      'Journeyman Rock Quarrier',
      'Adept Rock Quarrier',
      'Expert Rock Quarrier',
      'Master Rock Quarrier',
      'Grandmaster Rock Quarrier',
      'Elder Rock Quarrier',
    ],
    wood: [
      'Wood Lumberjack',
      'Novice Wood Lumberjack',
      'Journeyman Wood Lumberjack',
      'Adept Wood Lumberjack',
      'Expert Wood Lumberjack',
      'Master Wood Lumberjack',
      'Grandmaster Wood Lumberjack',
      'Elder Wood Lumberjack',
    ],
    fish: [
      'Fisherman',
      'Trainee Fisherman',
      'Novice Fisherman',
      'Journeyman Fisherman',
      'Adept Fisherman',
      'Expert Fisherman',
      'Master Fisherman',
      'Grandmaster Fisherman',
      'Elder Fisherman',
    ],
  },
  // Refining
  refining: {
    weaver: [
      'Weaver',
      'Novice Weaver',
      'Journeyman Weaver',
      'Adept Weaver',
      'Expert Weaver',
      'Master Weaver',
      'Grandmaster Weaver',
      'Elder Weaver',
    ],
    tanner: [
      'Tanner',
      'Novice Tanner',
      'Journeyman Tanner',
      'Adept Tanner',
      'Expert Tanner',
      'Master Tanner',
      'Grandmaster Tanner',
      'Elder Tanner',
    ],
    smelter: [
      'Smelter',
      'Novice Smelter',
      'Journeyman Smelter',
      'Adept Smelter',
      'Expert Smelter',
      'Master Smelter',
      'Grandmaster Smelter',
      'Elder Smelter',
    ],
    stonemason: [
      'Stonemason',
      'Novice Stonemason',
      'Journeyman Stonemason',
      'Adept Stonemason',
      'Expert Stonemason',
      'Master Stonemason',
      'Grandmaster Stonemason',
      'Elder Stonemason',
    ],
    woodworker: [
      'Woodworker',
      'Novice Woodworker',
      'Journeyman Woodworker',
      'Adept Woodworker',
      'Expert Woodworker',
      'Master Woodworker',
      'Grandmaster Woodworker',
      'Elder Woodworker',
    ],
  },
  // Crafting
  crafting: {
    toolmaker: [
      'Toolmaker',
      'Novice Toolmaker',
      'Journeyman Toolmaker',
      'Adept Toolmaker',
      'Expert Toolmaker',
      'Master Toolmaker',
      'Grandmaster Toolmaker',
      'Elder Toolmaker',
    ],
    axeCrafter: [
      'Axe Crafter',
      'Adept Axe Crafter',
      'Expert Axe Crafter',
      'Master Axe Crafter',
      'Grandmaster Axe Crafter',
      'Elder Axe Crafter',
    ],
    swordCrafter: [
      'Sword Crafter',
      'Adept Sword Crafter',
      'Expert Sword Crafter',
      'Master Sword Crafter',
      'Grandmaster Sword Crafter',
      'Elder Sword Crafter',
    ],
    maceCrafter: [
      'Mace Crafter',
      'Adept Mace Crafter',
      'Expert Mace Crafter',
      'Master Mace Crafter',
      'Grandmaster Mace Crafter',
      'Elder Mace Crafter',
    ],
    hammerCrafter: [
      'Hammer Crafter',
      'Adept Hammer Crafter',
      'Expert Hammer Crafter',
      'Master Hammer Crafter',
      'Grandmaster Hammer Crafter',
      'Elder Hammer Crafter',
    ],
    crossbowCrafter: [
      'Crossbow Crafter',
      'Adept Crossbow Crafter',
      'Expert Crossbow Crafter',
      'Master Crossbow Crafter',
      'Grandmaster Crossbow Crafter',
      'Elder Crossbow Crafter',
    ],
    bowCrafter: [
      'Bow Crafter',
      'Adept Bow Crafter',
      'Expert Bow Crafter',
      'Master Bow Crafter',
      'Grandmaster Bow Crafter',
      'Elder Bow Crafter',
    ],
    spearCrafter: [
      'Spear Crafter',
      'Adept Spear Crafter',
      'Expert Spear Crafter',
      'Master Spear Crafter',
      'Grandmaster Spear Crafter',
      'Elder Spear Crafter',
    ],
    daggerCrafter: [
      'Dagger Crafter',
      'Adept Dagger Crafter',
      'Expert Dagger Crafter',
      'Master Dagger Crafter',
      'Grandmaster Dagger Crafter',
      'Elder Dagger Crafter',
    ],
    quarterstaffCrafter: [
      'Quarterstaff Crafter',
      'Adept Quarterstaff Crafter',
      'Expert Quarterstaff Crafter',
      'Master Quarterstaff Crafter',
      'Grandmaster Quarterstaff Crafter',
      'Elder Quarterstaff Crafter',
    ],
    firestaffCrafter: [
      'Fire Staff Crafter',
      'Adept Fire Staff Crafter',
      'Expert Fire Staff Crafter',
      'Master Fire Staff Crafter',
      'Grandmaster Fire Staff Crafter',
      'Elder Fire Staff Crafter',
    ],
    holystaffCrafter: [
      'Holy Staff Crafter',
      'Adept Holy Staff Crafter',
      'Expert Holy Staff Crafter',
      'Master Holy Staff Crafter',
      'Grandmaster Holy Staff Crafter',
      'Elder Holy Staff Crafter',
    ],
    arcanestaffCrafter: [
      'Arcane Staff Crafter',
      'Adept Arcane Staff Crafter',
      'Expert Arcane Staff Crafter',
      'Master Arcane Staff Crafter',
      'Grandmaster Arcane Staff Crafter',
      'Elder Arcane Staff Crafter',
    ],
    froststaffCrafter: [
      'Frost Staff Crafter',
      'Adept Frost Staff Crafter',
      'Expert Frost Staff Crafter',
      'Master Frost Staff Crafter',
      'Grandmaster Frost Staff Crafter',
      'Elder Frost Staff Crafter',
    ],
    cursedstaffCrafter: [
      'Cursed Staff Crafter',
      'Adept Cursed Staff Crafter',
      'Expert Cursed Staff Crafter',
      'Master Cursed Staff Crafter',
      'Grandmaster Cursed Staff Crafter',
      'Elder Cursed Staff Crafter',
    ],
    naturestaffCrafter: [
      'Nature Staff Crafter',
      'Adept Nature Staff Crafter',
      'Expert Nature Staff Crafter',
      'Master Nature Staff Crafter',
      'Grandmaster Nature Staff Crafter',
      'Elder Nature Staff Crafter',
    ],
    plateArmorCrafter: [
      'Plate Armor Crafter',
      'Adept Plate Armor Crafter',
      'Expert Plate Armor Crafter',
      'Master Plate Armor Crafter',
      'Grandmaster Plate Armor Crafter',
      'Elder Plate Armor Crafter',
    ],
    leatherArmorCrafter: [
      'Leather Armor Crafter',
      'Adept Leather Armor Crafter',
      'Expert Leather Armor Crafter',
      'Master Leather Armor Crafter',
      'Grandmaster Leather Armor Crafter',
      'Elder Leather Armor Crafter',
    ],
    clothArmorCrafter: [
      'Cloth Armor Crafter',
      'Adept Cloth Armor Crafter',
      'Expert Cloth Armor Crafter',
      'Master Cloth Armor Crafter',
      'Grandmaster Cloth Armor Crafter',
      'Elder Cloth Armor Crafter',
    ],
    offhandCrafter: [
      'Off-hand Crafter',
      'Adept Off-hand Crafter',
      'Expert Off-hand Crafter',
      'Master Off-hand Crafter',
      'Grandmaster Off-hand Crafter',
      'Elder Off-hand Crafter',
    ],
    cook: [
      'Cook',
      'Trainee Cook',
      'Novice Cook',
      'Journeyman Cook',
      'Adept Cook',
      'Expert Cook',
      'Master Cook',
      'Grandmaster Cook',
      'Elder Cook',
    ],
    alchemist: [
      'Alchemist',
      'Trainee Alchemist',
      'Novice Alchemist',
      'Journeyman Alchemist',
      'Adept Alchemist',
      'Expert Alchemist',
      'Master Alchemist',
      'Grandmaster Alchemist',
      'Elder Alchemist',
    ],
  },
  // Farming
  farming: {
    crops: [
      'Crop Farmer',
      'Novice Crop Farmer',
      'Journeyman Crop Farmer',
      'Adept Crop Farmer',
      'Expert Crop Farmer',
      'Master Crop Farmer',
      'Grandmaster Crop Farmer',
      'Elder Crop Farmer',
    ],
    animals: [
      'Animal Breeder',
      'Journeyman Animal Breeder',
      'Adept Animal Breeder',
      'Expert Animal Breeder',
      'Master Animal Breeder',
      'Grandmaster Animal Breeder',
      'Elder Animal Breeder',
    ],
  },
} as const
