/**
 * Destiny Board Node Names for mapping
 * Used by destinyMapping.ts for character sync
 */

// Organized by category
export const DESTINY_BOARD_NODES = {
  // Warrior Weapons
  warrior: {
    axe: [
      'Axe Fighter',
      'Battleaxe Combat Specialist',
      'Greataxe Combat Specialist',
      'Halberd Combat Specialist',
      'Carrioncaller Combat Specialist',
      'Infernal Scythe Combat Specialist',
      'Bear Paws Combat Specialist',
      'Realmbreaker Combat Specialist',
    ],
    sword: [
      'Sword Fighter',
      'Broadsword Combat Specialist',
      'Claymore Combat Specialist',
      'Dual Swords Combat Specialist',
      'Clarent Blade Combat Specialist',
      'Carving Sword Combat Specialist',
      'Galatine Pair Combat Specialist',
      'Kingmaker Combat Specialist',
    ],
    mace: [
      'Mace Fighter',
      'Mace Combat Specialist',
      'Heavy Mace Combat Specialist',
      'Morning Star Combat Specialist',
      'Bedrock Mace Combat Specialist',
      'Incubus Mace Combat Specialist',
      'Camlann Mace Combat Specialist',
      'Oathkeepers Combat Specialist',
    ],
    hammer: [
      'Hammer Fighter',
      'Hammer Combat Specialist',
      'Polehammer Combat Specialist',
      'Great Hammer Combat Specialist',
      'Tombhammer Combat Specialist',
      'Forge Hammers Combat Specialist',
      'Grovekeeper Combat Specialist',
      'Hand of Justice Combat Specialist',
    ],
    wargloves: [
      'War Gloves Fighter',
      'Brawler Gloves Combat Specialist',
      'Battle Bracers Combat Specialist',
      'Spiked Gauntlets Combat Specialist',
      'Ravenstrike Cestus Combat Specialist',
      'Hellfire Hands Combat Specialist',
      'Fists of Avalon Combat Specialist',
      'Ursine Maulers Combat Specialist',
    ],
  },
  // Hunter Weapons
  hunter: {
    bow: [
      'Bow Fighter',
      'Bow Combat Specialist',
      'Warbow Combat Specialist',
      'Longbow Combat Specialist',
      'Whispering Bow Combat Specialist',
      'Wailing Bow Combat Specialist',
      'Bow of Badon Combat Specialist',
      'Mistpiercer Combat Specialist',
    ],
    crossbow: [
      'Crossbow Fighter',
      'Crossbow Combat Specialist',
      'Heavy Crossbow Combat Specialist',
      'Light Crossbow Combat Specialist',
      'Weeping Repeater Combat Specialist',
      'Boltcasters Combat Specialist',
      'Siegebow Combat Specialist',
      'Energy Shaper Combat Specialist',
    ],
    spear: [
      'Spear Fighter',
      'Spear Combat Specialist',
      'Pike Combat Specialist',
      'Glaive Combat Specialist',
      'Heron Spear Combat Specialist',
      'Spirithunter Combat Specialist',
      'Trinity Spear Combat Specialist',
      'Daybreaker Combat Specialist',
    ],
    dagger: [
      'Dagger Fighter',
      'Dagger Combat Specialist',
      'Dagger Pair Combat Specialist',
      'Claws Combat Specialist',
      'Bloodletter Combat Specialist',
      'Black Hands Combat Specialist',
      'Deathgivers Combat Specialist',
      'Bridled Fury Combat Specialist',
    ],
    quarterstaff: [
      'Quarterstaff Fighter',
      'Quarterstaff Combat Specialist',
      'Iron-clad Staff Combat Specialist',
      'Double Bladed Staff Combat Specialist',
      'Black Monk Stave Combat Specialist',
      'Soulscythe Combat Specialist',
      'Staff of Balance Combat Specialist',
      'Grailseeker Combat Specialist',
    ],
  },
  // Mage Weapons
  mage: {
    firestaff: [
      'Fire Staff Fighter',
      'Fire Staff Combat Specialist',
      'Great Fire Staff Combat Specialist',
      'Infernal Staff Combat Specialist',
      'Wildfire Staff Combat Specialist',
      'Blazing Staff Combat Specialist',
      'Brimstone Staff Combat Specialist',
      'Dawnsong Combat Specialist',
    ],
    holystaff: [
      'Holy Staff Fighter',
      'Holy Staff Combat Specialist',
      'Great Holy Staff Combat Specialist',
      'Divine Staff Combat Specialist',
      'Lifetouch Staff Combat Specialist',
      'Fallen Staff Combat Specialist',
      'Redemption Staff Combat Specialist',
      'Hallowfall Combat Specialist',
    ],
    arcanestaff: [
      'Arcane Staff Fighter',
      'Arcane Staff Combat Specialist',
      'Great Arcane Staff Combat Specialist',
      'Enigmatic Staff Combat Specialist',
      'Witchwork Staff Combat Specialist',
      'Occult Staff Combat Specialist',
      'Malevolent Locus Combat Specialist',
      'Evensong Combat Specialist',
    ],
    froststaff: [
      'Frost Staff Fighter',
      'Frost Staff Combat Specialist',
      'Great Frost Staff Combat Specialist',
      'Glacial Staff Combat Specialist',
      'Hoarfrost Staff Combat Specialist',
      'Icicle Staff Combat Specialist',
      'Permafrost Prism Combat Specialist',
      'Chillhowl Combat Specialist',
    ],
    cursedstaff: [
      'Cursed Staff Fighter',
      'Cursed Staff Combat Specialist',
      'Great Cursed Staff Combat Specialist',
      'Demonic Staff Combat Specialist',
      'Cursed Skull Combat Specialist',
      'Damnation Staff Combat Specialist',
      'Lifecurse Staff Combat Specialist',
      'Shadowcaller Combat Specialist',
    ],
    naturestaff: [
      'Nature Staff Fighter',
      'Nature Staff Combat Specialist',
      'Great Nature Staff Combat Specialist',
      'Wild Staff Combat Specialist',
      'Druidic Staff Combat Specialist',
      'Blight Staff Combat Specialist',
      'Rampant Staff Combat Specialist',
      'Ironroot Staff Combat Specialist',
    ],
  },
  // Plate Armor
  plate: {
    helmet: [
      'Plate Helmet Fighter',
      'Soldier Helmet Specialist',
      'Knight Helmet Specialist',
      'Guardian Helmet Specialist',
      'Royal Helmet Specialist',
      'Demon Helmet Specialist',
      'Judicator Helmet Specialist',
      'Helmet of Valor Specialist',
    ],
    armor: [
      'Plate Armor Fighter',
      'Soldier Armor Specialist',
      'Knight Armor Specialist',
      'Guardian Armor Specialist',
      'Royal Armor Specialist',
      'Demon Armor Specialist',
      'Judicator Armor Specialist',
      'Armor of Valor Specialist',
    ],
    boots: [
      'Plate Boots Fighter',
      'Soldier Boots Specialist',
      'Knight Boots Specialist',
      'Guardian Boots Specialist',
      'Royal Boots Specialist',
      'Demon Boots Specialist',
      'Judicator Boots Specialist',
      'Boots of Valor Specialist',
    ],
  },
  // Leather Armor
  leather: {
    hood: [
      'Leather Hood Fighter',
      'Mercenary Hood Specialist',
      'Hunter Hood Specialist',
      'Assassin Hood Specialist',
      'Hood of Tenacity Specialist',
      'Hellion Hood Specialist',
      'Stalker Hood Specialist',
      'Specter Hood Specialist',
    ],
    jacket: [
      'Leather Jacket Fighter',
      'Mercenary Jacket Specialist',
      'Hunter Jacket Specialist',
      'Assassin Jacket Specialist',
      'Jacket of Tenacity Specialist',
      'Hellion Jacket Specialist',
      'Stalker Jacket Specialist',
      'Specter Jacket Specialist',
    ],
    shoes: [
      'Leather Shoes Fighter',
      'Mercenary Shoes Specialist',
      'Hunter Shoes Specialist',
      'Assassin Shoes Specialist',
      'Shoes of Tenacity Specialist',
      'Hellion Shoes Specialist',
      'Stalker Shoes Specialist',
      'Specter Shoes Specialist',
    ],
  },
  // Cloth Armor
  cloth: {
    cowl: [
      'Cloth Cowl Fighter',
      'Scholar Cowl Specialist',
      'Cleric Cowl Specialist',
      'Mage Cowl Specialist',
      'Royal Cowl Specialist',
      'Fiend Cowl Specialist',
      'Cultist Cowl Specialist',
      'Cowl of Purity Specialist',
    ],
    robe: [
      'Cloth Robe Fighter',
      'Scholar Robe Specialist',
      'Cleric Robe Specialist',
      'Mage Robe Specialist',
      'Royal Robe Specialist',
      'Fiend Robe Specialist',
      'Cultist Robe Specialist',
      'Robe of Purity Specialist',
    ],
    sandals: [
      'Cloth Sandals Fighter',
      'Scholar Sandals Specialist',
      'Cleric Sandals Specialist',
      'Mage Sandals Specialist',
      'Royal Sandals Specialist',
      'Fiend Sandals Specialist',
      'Cultist Sandals Specialist',
      'Sandals of Purity Specialist',
    ],
  },
  // Off-hand
  offhand: {
    shield: [
      'Shield Fighter',
      'Shield Specialist',
      'Sarcophagus Specialist',
      'Caitiff Shield Specialist',
      'Facebreaker Specialist',
      'Astral Aegis Specialist',
    ],
    torch: [
      'Torch Fighter',
      'Torch Specialist',
      'Mistcaller Specialist',
      'Leering Cane Specialist',
      'Cryptcandle Specialist',
      'Sacred Scepter Specialist',
    ],
    tome: [
      'Tome Fighter',
      'Tome of Spells Specialist',
      'Eye of Secrets Specialist',
      'Muisak Specialist',
      'Taproot Specialist',
      'Celestial Censer Specialist',
    ],
  },
} as const
